-- ============================================================
-- schema.sql
-- Esquema relacional para SQL Server / Azure SQL
-- Compatible con la actividad académica de predicción de ventas
-- ============================================================

IF OBJECT_ID('dbo.ML_SALES_FORECAST_DETAIL', 'U') IS NOT NULL
    DROP TABLE dbo.ML_SALES_FORECAST_DETAIL;
GO

IF OBJECT_ID('dbo.ML_SALES_FORECAST_RUN', 'U') IS NOT NULL
    DROP TABLE dbo.ML_SALES_FORECAST_RUN;
GO

CREATE TABLE dbo.ML_SALES_FORECAST_RUN (
    RUN_ID INT IDENTITY(1,1) PRIMARY KEY,
    MODEL_NAME VARCHAR(100) NOT NULL,
    TRAINING_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    TRAIN_FROM_DATE DATE NULL,
    TRAIN_TO_DATE DATE NULL,
    TEST_FROM_DATE DATE NULL,
    TEST_TO_DATE DATE NULL,
    MAE FLOAT NULL,
    RMSE FLOAT NULL,
    R2 FLOAT NULL,
    MAPE FLOAT NULL,
    OBSERVATIONS_TRAIN INT NULL,
    OBSERVATIONS_TEST INT NULL
);
GO

CREATE TABLE dbo.ML_SALES_FORECAST_DETAIL (
    FORECAST_ID INT IDENTITY(1,1) PRIMARY KEY,
    RUN_ID INT NOT NULL,
    FORECAST_DATE DATE NOT NULL,
    PRODUCT_CODE VARCHAR(50) NULL,
    PRODUCT_NAME VARCHAR(255) NULL,
    CATEGORY_NAME VARCHAR(255) NULL,
    WAREHOUSE_NAME VARCHAR(255) NULL,
    ZONE_NAME VARCHAR(255) NULL,
    SALESMAN_NAME VARCHAR(255) NULL,
    REAL_SALES FLOAT NULL,
    PREDICTED_SALES FLOAT NOT NULL,
    ABSOLUTE_ERROR FLOAT NULL,
    PERCENTAGE_ERROR FLOAT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (RUN_ID) REFERENCES dbo.ML_SALES_FORECAST_RUN(RUN_ID)
);
GO

-- Vista resumen diaria para BI (real vs predicho)
CREATE VIEW dbo.VW_FORECAST_DAILY_SUMMARY AS
SELECT
    FORECAST_DATE,
    SUM(REAL_SALES) AS TOTAL_REAL_SALES,
    SUM(PREDICTED_SALES) AS TOTAL_PREDICTED_SALES,
    SUM(ABSOLUTE_ERROR) AS TOTAL_ABSOLUTE_ERROR,
    CASE WHEN SUM(REAL_SALES) > 0 THEN SUM(ABSOLUTE_ERROR) / SUM(REAL_SALES) * 100 ELSE 0 END AS MAPE_DAILY
FROM dbo.ML_SALES_FORECAST_DETAIL
WHERE REAL_SALES IS NOT NULL
GROUP BY FORECAST_DATE;
GO

-- Vista resumen mensual futuro
CREATE VIEW dbo.VW_FORECAST_FUTURE_MONTHLY AS
SELECT
    FORMAT(FORECAST_DATE, 'yyyy-MM') AS MONTH_KEY,
    SUM(PREDICTED_SALES) AS TOTAL_PREDICTED_SALES
FROM dbo.ML_SALES_FORECAST_DETAIL
WHERE REAL_SALES IS NULL
GROUP BY FORMAT(FORECAST_DATE, 'yyyy-MM');
GO
